#ifndef __PRGGENERATOR_H_
#define __PRGGENERATOR_H_

#define ASS_SIZE        0x0183
#define SCREEN_SIZE     0x1000
#define CHAR_SIZE       0x0800

#define BASEADDRESS     0x1C01
#define VERSIONADDRESS  0x3D

#define BGCOLORADDRESS  0x1C7B
#define CHARSTDADDRESS  0x1C7C
#define CHARALTADDRESS  0x1C7E

#endif // __PRGGENERATOR_H_